import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react";
import { GET } from "../src/utils/http";

// Layout
import Layout from "../src/Layout";

// components
import Hero from "../src/components/hero";
import CardList from "../src/components/cardList";

export default function Home() {
  const [data, setData] = useState([]);

  useEffect(() => {
    GET("games").then((data) => setData(data));
  }, []);

  useEffect(() => {
    console.log(data);
  }, [data]);

  return (
    <>
      <Head>
        <title>Games center</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className={styles.main}>
          <Hero />
          <CardList data={data} />
        </main>
      </Layout>
    </>
  );
}
