import Head from "next/head";
import styles from "@/styles/Home.module.css";

// Layout
import Layout from "@/src/Layout";

// components
import Hero from "@/src/components/hero";

export default function Home() {
  return (
    <>
      <Head>
        <title>Games center</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className={styles.main}>
          <Hero />
        </main>
      </Layout>
    </>
  );
}
